### ISSUE TITLE
`qiskit.test.decorators.enforce_subclasses_call` machinery is broken in 3.11.1

### ISSUE THREAD

**Issue by ihincks** [Qiskit/qiskit-terra#9291]
### Environment

- **Qiskit Terra version**: 

HEAD of main, currently `dd7f9390cf07`

- **Python version**: 

3.11.1

- **Operating system**: 

Both macOS and ubuntu, so far.

### What is happening?

`import test.python` raises an error in 3.11.1, therefore tests do not run. @wshanks has indicated that it is working fine for him in 3.11.0 but not 3.11.1 (I don't have 3.11.0 installed).

```
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test.python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ihincks/ibm/qiskit-terra/test/__init__.py", line 16, in <module>
    from qiskit.test.utils import generate_cases
  File "/Users/ihincks/ibm/qiskit-terra/qiskit/test/__init__.py", line 15, in <module>
    from .base import QiskitTestCase
  File "/Users/ihincks/ibm/qiskit-terra/qiskit/test/base.py", line 167, in <module>
    class QiskitTestCase(BaseQiskitTestCase):
  File "/Users/ihincks/ibm/qiskit-terra/qiskit/utils/classtools.py", line 117, in out
    retval = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase.__init_subclass__() missing 1 required positional argument: 'cls'
```

Or, see an example of this happening in CI: https://github.com/Qiskit/qiskit-experiments/actions/runs/3704009805/jobs/6281449337

### How can we reproduce the issue?

Run the tests or simply `import test.python` in Python 3.11.1.

### What should happen?

This should not error.

**Comment by ihincks** [comment]
I'm having trouble reproducing this using only `wrap_method`. For example, the following works as expected:
```python
import qiskit.utils

class Foo: 
    pass

def print_blerg(*_): 
    print("blerg")

qiskit.utils.classtools.wrap_method(Foo, "__init_subclass__", after=print_blerg)

class Goo(Foo):
    pass
```

**Comment by Cryoris** [comment]
If it works on 3.11.0 maybe https://github.com/python/cpython/pull/99646 is related which touches `TestCase.__init_subclass__`? Though it's weird that the failure isn't happening consistently, in some of the CI runs only Mac and in some only Linux failed..

**Comment by 1ucian0** [comment]
please, revert https://github.com/Qiskit/qiskit-terra/pull/9296 when fixed.

**Comment by ihincks** [comment]
I did a bit more digging and I think that https://github.com/python/cpython/pull/99646 is, surprisingly, unrelated to issue. I believe there has been a change in Python itself that breaks the way `qiskit.utils._WrappedMethod.__get__` deals with `__init_subclass__`. I can't find the change in the 3.11.1 changelog, but didn't look as hard as I could have. That the change to `TestCase` appears in the same release is just bad luck.

Consider the following:
```python
class Foo:
    def __init_subclass__(cls, *args, **kwargs):
        ...
        
method = type.__getattribute__(Foo, "__init_subclass__").__get__(None, Foo)
print(method)
method()
``` 

This snippet summarizes the path that qiskit's `wrap_method` and `_WrappedMethod` take to grab  the underlying `__init_subclass__` method. In Python 3.11.1,`method` as defined above is not a bound method, but in previous Python versions, it is. Hence the `TypeError` when it's called without `cls` as the first argument.

**Comment by jakelishman** [comment]
Looking back, I think I over-engineered this machinery in response to a minor problem, mostly because I was enjoying learning more of the Python internals. That said, at the top of the file there's some special handling for the magic methods that lie about their implementations; you might be able to fix this by adding the `__init_subclass__` string to the relevant set at the top of the file, if it's now an implicit class method rather than explicit one.

**Comment by wshanks** [comment]
Yes, I think the issue requires both the unittest change and a change to how `__init_subclass__` is treated in 3.11. `__init_subclass__` is a weird case that gets converted into a classmethod (according to the documentation; what that actually means I am not sure and I think might have changed in 3.11) and I think the decorator/wrapper code might mischaracterize it now.

**Comment by wshanks** [comment]
#9310 is a test of that idea.

**Comment by ihincks** [comment]
I think something like this might work across versions, but I've never run terra tests locally and running into possibly superficial issues (circular imports do to _accellerate):

```diff
--- a/qiskit/utils/classtools.py
+++ b/qiskit/utils/classtools.py
@@ -101,14 +101,15 @@ class _WrappedMethod:
             self._method = method
         # If the inner method doesn't have `__get__` (like some builtin methods), it's faster to
         # test a Boolean each time than the repeatedly raise and catch an exception, which is what
-        # `hasattr` does.
-        self._method_has_get = hasattr(self._method, "__get__")
+        # `hasattr` does. Moreover, depending on the Python version, some magic methods' `__get__`
+        # method return an unbound version of the method, which we avoid by also checking `__self__`
+        self._use_get = hasattr(self._method, "__get__") and not hasattr(self._method, "__self__")
 
     def __get__(self, obj, objtype=None):
         # `self._method` doesn't invoke the `_method` descriptor (if it is one) because that only
         # happens for class variables. Here it's an instance variable, so we can pass through `obj`
         # and `objtype` correctly like this.
-        method = self._method.__get__(obj, objtype) if self._method_has_get else self._method
+        method = self._method.__get__(obj, objtype) if self._use_get else self._method
 
         @functools.wraps(method)
         def out(*args, **kwargs):
```

**Comment by wshanks** [comment]
`qiskit.test.decorators.enforce_subclasses_call` is a class decorator that wraps specified methods of the class in wrappers that set a flag when the method is called and wraps `__init_subclass__` in a wrapper that then wraps those methods on subclasses to clear the flags and then make sure the flags are set after the call.

The wrapper code distinguishes between methods defined on `type` and other methods and uses `type.__getattribute__` or `object.__getattribute__` accordingly [here](https://github.com/Qiskit/qiskit-terra/blob/07e0a2fc79bada7c1fbf0594f4ad33934f70b7e2/qiskit/utils/classtools.py#L152). This is the part I don't completely follow (though there are nice comments by the code). I can't find documentation on the difference between `type.__getattribute__` and `object.__getattribute__` (beyond reading the Python source code). I think that something funny happens with `__init_subclass__` between the way it gets converted to a classmethod and the way it is bound to the class variable. The change in behavior might be related to the performance work that was done in 3.11 which I think worked on optimizing attribute access.

This code mimics how the qiskit method wrapper handles type methods and other methods:

```
class CustomInitSubclass:
    def __init_subclass__(cls, *args, **kwargs):
        super().__init_subclass__()



print(
    "type getter",
    type.__getattribute__(
        CustomInitSubclass,
        "__init_subclass__",
    ).__get__(None, CustomInitSubclass)
)

print(
    "object getter",
    object.__getattribute__(
        CustomInitSubclass,
        "__init_subclass__",
    ).__get__(None, CustomInitSubclass)
)
```

On 3.10, I see

```
type getter <bound method CustomInitSubclass.__init_subclass__ of <class '__main__.CustomInitSubclass'>>
object getter <bound method CustomInitSubclass.__init_subclass__ of <class '__main__.CustomInitSubclass'>>
```

while on 3.11 I see:

```
type getter <function CustomInitSubclass.__init_subclass__ at 0x7f2a321987c0>
object getter <bound method CustomInitSubclass.__init_subclass__ of <class '__main__.CustomInitSubclass'>>
```

In #9310, I just force `__init_subclass__` back to the `object` getter instead of the `type` one. There may be more that is good to adjust by someone who understood the distinction between `object.__getattribute__` and `type.__getattribute__` better than I do.

**Comment by wshanks** [comment]
@ihincks When I see a message about `_accelerate`, it is usually because I forgot to run `pip install .` after switching branches or Python versions (because it is the first compiled thing that is imported).

**Comment by jakelishman** [comment]
I can't remember all the details off the top of my head, but I'm fairly sure the differences are in how they apply the descriptor protocol - `object.__getattribute__` fills in the fields like instance calls, and `type.__getattribute__` fills in the fields as if they're class calls (because of course that's what's happening).  They have slightly different interplay with `__new__`, `__init_subclass__` and `__prepare__`, which are "magic" descriptors (they bind differently to how their definitions would appear), but I can't remember / maybe never knew what that is.

**Comment by ihincks** [comment]
There's a bit of description [here](https://docs.python.org/3/howto/descriptor.html#invocation-from-a-class) (and near here). If @wshanks patch passes tests I'll personally be happy, because it's unlikely that these machines will ever test the magic methods in ways beyond `enforce_subclass_call` currently does 😄

**Comment by wshanks** [comment]
My original suggestion was actually wrong and the one from @ihincks was closer to the right solution. Mine "worked" but only by chance for the specific circumstances covered by the tests. By forcing `__init_subclass__` back to `object.__getattribute__`, I just forced the wrapper to call `object.__init_subclass__` instead of the wrapped class's method. For the tests, that had the effect of just bypassing `unittest.TestCase.__init_subclass__` (the only wrapping of `__init_subclass__` in the tests) which does not do much so was not missed by the tests, but bypassing `__init_subclass__` obviously would cause problems if anyone ever wanted to use `__init_subclass__`. I described the issue in #9310 in detail. The short version is that the classmethod was getting converted to a bound method by `__getattribute__` and then unbound by `__get__`. Ian's solution detects the classmethod to bound method conversion by checking for `__self__` and skips the call to `__get__` that unbinds the function. #9310 instead avoids the classmethod to bound method conversion by avoiding `__getattribute__`.
