### PR TITLE
Docathon: pulse visualizer

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary
Docstring update for pulse visualizer module.

### CODE REVIEW

File: qiskit/visualization/pulse/interpolation.py [hunk 1]
```diff
@@ -30,8 +30,8 @@ def interp1d(time, samples, nop, kind='linear'):
         time (ndarray): time.
         samples (ndarray): complex pulse envelope.
         nop (int): data points for interpolation.
-        kind (str): Scipy interpolation type. See `scipy.interpolate.interp1d` documentation
-            for more information.
+        kind (str): Scipy interpolation type.
+            See `scipy.interpolate.interp1d` documentation for more information.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/interpolation.py]:
```suggestion
            See ``scipy.interpolate.interp1d`` documentation for more information.
```

File: qiskit/visualization/pulse/interpolation.py [hunk 2]
```diff
@@ -50,7 +50,34 @@ def interp1d(time, samples, nop, kind='linear'):
 
 
 linear = partial(interp1d, kind='linear')
+linear.__doc__ = """Apply linear interpolation between sampling points.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/interpolation.py]: I don't think `__doc__` is supposed to be explicitly assigned to. What problem are you trying to solve here?

File: qiskit/visualization/pulse/matplotlib.py [hunk 3]
```diff
@@ -219,27 +222,29 @@ def _trim(self, events):
...
-            scaling (float): Deprecated, see `scale`
+            pulse: SamplePulse to draw.
+            dt: time interval.
+            interp_method: interpolation function.
+            scale: Relative visual scaling of waveform amplitudes.
+            scaling: Deprecated, see `scale`.
 
         Returns:
-            matplotlib.figure: A matplotlib figure object of the pulse envelope
+            matplotlib.Figure: A matplotlib figure object of the pulse envelope.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
            A matplotlib figure object of the pulse envelope.
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 4]
```diff
@@ -281,15 +286,35 @@ def draw(self, pulse, dt, interp_method, scale=1, scaling=None):
...
-            style (SchedStyle): style sheet
+            style: Style sheet for pulse schedule visualization.
         """
         self.style = style or SchedStyle()
 
-    def _build_channels(self, schedule, channels, t0, tf, show_framechange_channels=True):
+    def _build_channels(self, schedule: 'ScheduleComponent',
+                        channels: List['Channel'],
+                        t0: int, tf: int,
+                        show_framechange_channels: bool = True)\
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]: I think I usually see this in this situation:
```
       arg: type
) -> Tuple[...
```
with a newline before the `)` and no indentation

File: qiskit/visualization/pulse/matplotlib.py [hunk 5]
```diff
@@ -281,15 +286,35 @@ def draw(self, pulse, dt, interp_method, scale=1, scaling=None):
...
+            -> Tuple[Dict['Channel', EventsOutputChannels],
+                     Dict['Channel', EventsOutputChannels],
+                     Dict['Channel', EventsOutputChannels]]:
+        """ Create event table of each pulse channels in the given schedule.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
        """Create event table of each pulse channels in the given schedule.
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 6]
```diff
@@ -350,10 +375,27 @@ def _build_channels(self, schedule, channels, t0, tf, show_framechange_channels=
...
         return channels, output_channels, snapshot_channels
 
-    def _count_valid_waveforms(self, output_channels, scale, channel_scales=None,
-                               channels=None, plot_all=False):
+    @staticmethod
+    def _scale_channels(output_channels: Dict['Channel', EventsOutputChannels],
+                        scale: float,
+                        channel_scales: Dict['Channel', float] = None,
+                        channels: List['Channel'] = None,
+                        plot_all: bool = False)\
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
                        plot_all: bool = False) -> Dict['Channel', float]:
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 7]
```diff
@@ -384,10 +424,21 @@ def _count_valid_waveforms(self, output_channels, scale, channel_scales=None,
             else:
                 scale_dict[channel] = scale_val
 
-        return n_valid_waveform, scale_dict
+        return scale_dict
+
+    def _draw_table(self, figure: 'matplotlib.figure.Figure',
+                    channels: Dict['Channel', EventsOutputChannels],
+                    dt: float) -> 'matplotlib.axes.Axes':
+        """ Draw event table if events exist.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
        """Draw event table if events exist.
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 8]
```diff
@@ -444,23 +495,50 @@ def _draw_table(self, figure, channels, dt, n_valid_waveform):
 
         return ax
 
-    def _draw_snapshots(self, ax, snapshot_channels, dt, y0):
+    @staticmethod
+    def _draw_snapshots(ax: 'matplotlib.axes.Axes',
+                        snapshot_channels: Dict['Channel', EventsOutputChannels],
+                        dt: float, y0: float) -> NoReturn:
+        """ Draw snapshots to given mpl axis.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]: here too, and a few other places

**Comment by lcapelluto** [comment]
This is so helpful! :D

File: qiskit/visualization/pulse/interpolation.py (hunk 2 above)
Comment (nkanazawa1989) [reply qiskit/visualization/pulse/interpolation.py]: This creats interpolation function by partial binding of `kind` because visualizer only receives callable. We need to prepare unique docstring for each interpolation function.

File: qiskit/visualization/pulse/matplotlib.py (hunk 4 above)
Comment (nkanazawa1989) [reply qiskit/visualization/pulse/matplotlib.py]: ok, I'll update them.

File: qiskit/visualization/pulse/matplotlib.py (hunk 8 above)
Comment (nkanazawa1989) [reply qiskit/visualization/pulse/matplotlib.py]: all done.

File: qiskit/visualization/pulse/matplotlib.py [hunk 9]
```diff
@@ -384,10 +423,21 @@ def _count_valid_waveforms(self, output_channels, scale, channel_scales=None,
...
 
-    # pylint: disable=unused-argument
-    def _draw_table(self, figure, channels, dt, n_valid_waveform):
+        Args:
+            figure: Figure object
+            channels: Dictionary of channel and event table
+            dt: Time interval
+
+        Returns:
+            ax: Axis object for drawing pulses.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
            Axis object for drawing pulses.
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 10]
```diff
@@ -444,23 +494,50 @@ def _draw_table(self, figure, channels, dt, n_valid_waveform):
...
             if snapshots:
                 for time in snapshots:
                     ax.annotate(s=u"\u25D8", xy=(time*dt, y0), xytext=(time*dt, y0+0.08),
                                 arrowprops={'arrowstyle': 'wedge'}, ha='center')
 
-    def _draw_framechanges(self, ax, fcs, dt, y0):
-        framechanges_present = True
+    def _draw_framechanges(self, ax: 'matplotlib.axes.Axes',
+                           fcs: Dict[int, 'FrameChangeInstruction'],
+                           dt: float, y0: float) -> NoReturn:
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
                           dt: float, y0: float) -> None:
```

Interesting though, I'd never seen this before so I looked it up: https://docs.python.org/3/library/typing.html#typing.NoReturn

It's for functions that always error and never return.

File: qiskit/visualization/pulse/matplotlib.py [hunk 11]
```diff
@@ -444,23 +494,50 @@ def _draw_table(self, figure, channels, dt, n_valid_waveform):
...
 
-    def _get_channel_color(self, channel):
+    def _get_channel_color(self, channel: 'Channel') -> str:
+        """Lookup table for waveform color.
+
+        Args:
+            channel: Type of channel.
+
+        Return:
+            color: Color code or name of color.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
            Color code or name of color.
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 12]
```diff
@@ -474,14 +551,37 @@ def _get_channel_color(self, channel):
...
             for t0, (tf, _) in labels.items():
                 if time in (t0, tf):
                     return True
         return False
 
-    def _draw_labels(self, ax, labels, prev_labels, dt, y0):
+    def _draw_labels(self, ax: 'matplotlib.axes.Axes',
+                     labels: Dict[int, Union['SamplePulse', 'Acquire']],
+                     prev_labels: List[Dict[int, Union['SamplePulse', 'Acquire']]],
+                     dt: float, y0: float) -> NoReturn:
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
                     dt: float, y0: float) -> None:
```

File: qiskit/visualization/pulse/matplotlib.py [hunk 13]
```diff
@@ -507,8 +607,28 @@ def _draw_labels(self, ax, labels, prev_labels, dt, y0):
...
+            interp_method: Callback function for waveform interpolation.
+            t0: Start time of schedule.
+            tf: End time of schedule.
+            dt: Time interval.
+            scale_dict: Scale factor for each channel.
+            label: When set `True` draw labels.
+            framechange: When set `True` draw frame change symbols.
+
+        Return:
+            y0: Value of final vertical axis of canvas.
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
            Value of final vertical axis of canvas.
```
The name of the local variable used within the function and later returned doesn't have any meaning to the caller

File: qiskit/visualization/pulse/matplotlib.py [hunk 14]
```diff
@@ -572,35 +692,48 @@ def _draw_channels(self, ax, output_channels, interp_method, t0, tf, dt, scale_d
...
+            framechange: When set `True` draw framechange indicators.
+            scaling: Deprecated, see `scale`.
+            channels: A list of channel names to plot.
+                All non-empty channels are shown if not provided.
+            show_framechange_channels: When set `True` plot channels
+                with only framechange instructions.
 
         Returns:
-            matplotlib.figure: A matplotlib figure object for the pulse schedule
+            matplotlib.figure.Figure: A matplotlib figure object
```
Comment (lcapelluto) [inline qiskit/visualization/pulse/matplotlib.py]:
```suggestion
            A matplotlib figure object
```
this could be one line now
```suggestion
            A matplotlib figure object for the pulse envelope.
```
but the next line also has to be removed

File: qiskit/visualization/pulse/interpolation.py (hunk 2 above)
Comment (lcapelluto) [reply qiskit/visualization/pulse/interpolation.py]: Following our style rules, it should be documented like this:
```suggestion
"""Apply linear interpolation between sampling points.
```

But it's possible there's something complicating going on with sphinx that your way becomes necessary. Can you show me the diff between the current way and the above with the way that the docs are rendered?

Comment (nkanazawa1989) [reply qiskit/visualization/pulse/interpolation.py]: Current docstring viewed from jupyter notebook
```
Signature:      
linear(
    time:numpy.ndarray,
    samples:numpy.ndarray,
    nop:int,
    *,
    kind:str='linear',
) -> Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]
Call signature:  linear(*args, **kwargs)
Type:            partial
String form:     functools.partial(<function interp1d at 0x7f210b56c840>, kind='linear')
File:            /usr/lib/python3.6/functools.py
Docstring:      
Apply linear interpolation between sampling points.

Args:
    time (ndarray): time.
    samples (ndarray): complex pulse envelope.
    nop (int): data points for interpolation.
Returns:
    interpolated time vector and real and imaginary part of waveform.
Class docstring:
partial(func, *args, **keywords) - new function with partial application
of the given arguments and keywords.
```

and with your suggestion
```
Signature:     
linear(
    time:numpy.ndarray,
    samples:numpy.ndarray,
    nop:int,
    *,
    kind:str='linear',
) -> Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]
Call signature: linear(*args, **kwargs)
Type:           partial
String form:    functools.partial(<function interp1d at 0x7fd74cbfd400>, kind='linear')
File:           /usr/lib/python3.6/functools.py
Docstring:     
partial(func, *args, **keywords) - new function with partial application
of the given arguments and keywords
```

`tox -edocs` doesn't work in my local env due to import error.

**Comment by nkanazawa1989** [comment]
@lcapelluto Thank you for reviewing. I referred to this [stack overflow](https://stackoverflow.com/questions/27362727/partial-function-application-with-the-original-docstring-in-python) conversation for docstring of the partial functions.

File: qiskit/visualization/pulse_visualization.py [hunk 15]
```diff
@@ -26,39 +28,85 @@
...
-        matplotlib.figure: A matplotlib figure object for the pulse envelope
+        A matplotlib figure object for the pulse envelope.
+
+    Example:
+        This example shows how to customize your schedule plot.
+        Custom style sheet is applied and pulse names are added to the plot.
+        Unimportant channels are removed and the schedule is truncated to
+        draw out important pulses.
+
+        .. jupyter-execute::
```
Comment (SooluThomas) [inline qiskit/visualization/pulse_visualization.py]: A newline must be added after `.. jupyter-execute::` otherwise the build will fail. (The PR test builds didn't fail yet because API Doc for this file is not generated as it hasn't been added to the `qiskit.visualization.__init__.py`)

```suggestion
        .. jupyter-execute::
        
```

File: qiskit/visualization/pulse_visualization.py [hunk 16]
```diff
@@ -26,39 +28,85 @@
...
 
 
-def pulse_drawer(data, dt=1, style=None, filename=None,
-                 interp_method=None, scale=None, channel_scales=None,
-                 channels_to_plot=None, plot_all=False, plot_range=None,
-                 interactive=False, table=True, label=False, framechange=True,
-                 channels=None, scaling=None,
-                 show_framechange_channels=True):
-    """Plot the interpolated envelope of pulse
+def pulse_drawer(data: Union['SamplePulse', 'ScheduleComponent'],
```
Comment (SooluThomas) [inline qiskit/visualization/pulse_visualization.py]: To remove build warnings. (`WARNING: Cannot resolve forward reference in type annotations of "qiskit.visualization.pulse_drawer": name 'ScheduleComponent' is not defined`)

```suggestion
def pulse_drawer(data: Union[SamplePulse, ScheduleComponent],
```
Please import the necessary modules. Similarly, update `PulseStyle` and `SchedStyle`

File: qiskit/visualization/pulse_visualization.py [hunk 17]
```diff
@@ -26,39 +28,85 @@
...
-        label (bool): Label individual instructions
-        framechange (bool): Add framechange indicators
-        scaling (float): Deprecated, see `scale`
-        channels (list): A list of channel names to plot
-        show_framechange_channels (bool): Plot channels with only framechanges
+        data: Pulse or schedule object to plot.
+        dt: Time interval of samples. Pulses are visualized in the unit of
+            cycle time if not provided.
+        style: A style sheet to configure plot appearance.
+            See `qiskit.visualization.pulse.qcstyle` for more information.
```
Comment (SooluThomas) [inline qiskit/visualization/pulse_visualization.py]:
```suggestion
            See :mod:`~qiskit.visualization.pulse.qcstyle` for more information.
```

File: qiskit/visualization/__init__.py [hunk 18]
```diff
@@ -110,6 +110,8 @@
 
 from qiskit.visualization.transition_visualization import visualize_transition
 from .pulse_visualization import pulse_drawer
```
Comment (SooluThomas) [inline qiskit/visualization/__init__.py]: The docs for Pulse Visualization can be added when the API docs are generated. For doing so, add the below code to the docstrings in this file:
```
Pulse Visualizations
====================

.. autosummary::
   :toctree: ../stubs/

   pulse_drawer

.. autosummary::
   :hidden:
   :toctree: ../stubs/

   qiskit.visualization.pulse.qcstyle
   qiskit.visualization.pulse.interpolation
```

Screenshot:
image

File: qiskit/visualization/pulse_visualization.py [hunk 19]
```diff
@@ -26,39 +28,85 @@
...
+        filename: Name required to save pulse image. The drawer just returns
+            `matplot.Figure` object if not provided.
+        interp_method: Interpolation function. See example.
+            Interpolation is disabled in default.
+            See `qiskit.visualization.pulse.interpolation` for more information.
```
Comment (SooluThomas) [inline qiskit/visualization/pulse_visualization.py]:
```suggestion
            See :mod:`~qiskit.visualization.pulse.interpolation` for more information.
```

**Comment by nkanazawa1989** [comment]
@SooluThomas thanks for reviewing. I updated PR in accordance with your suggestions.

File: qiskit/visualization/pulse_visualization.py (hunk 16 above)
Comment (nkanazawa1989) [reply qiskit/visualization/pulse_visualization.py]: Type hinting in visualizer often cause cyclic import error. This time the error is very strange because `test/python/validation/__init__.py` never call visualization module. I'll check in detail this weekend.
https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=9107&view=logs&j=7684b0c9-af38-5400-184f-6880bd8a4dd7&t=9d95188b-4e59-58d8-f7c4-3f1fbd4209ad

File: qiskit/visualization/__init__.py [hunk 20]
```diff
@@ -80,6 +80,21 @@
...
+   :toctree: ../stubs/
+
+   pulse_drawer
+
+.. autosummary::
+   :hidden:
+   :toctree: ../stubs/
+
+   qiskit.visualization.pulse.qcstyle
+   qiskit.visualization.pulse.interpolation
```
Comment (SooluThomas) [inline qiskit/visualization/__init__.py]: Sorry, I'm not sure why I suggested hidden qcstyle and interpolation module. It's better to take not use `:hidden:` as suggested in the [comment](https://github.com/Qiskit/qiskit-terra/pull/3902#discussion_r385222829) as it's not a known option for autosummary directive.

```suggestion
   pulse_drawer
   ~qiskit.visualization.pulse.qcstyle
   ~qiskit.visualization.pulse.interpolation
```

**Comment by taalexander** [comment]
Is there an update on this? @SooluThomas do you think you could help push this over the finish line with @nkanazawa1989?

**Comment by nkanazawa1989** [comment]
@taalexander recently visualizer is frequently updated and my PR was outdated with many conflicts. I fixed all of them and removed type hints of mpl objects to pass Travis tests.

**Comment by nkanazawa1989** [comment]
looks like jupyter-execute in the docstring failed due to #4007. #4009 should be merged first.

**Comment by SooluThomas** [comment]
Yay! 🎉 I see that all the checks are passing. But weirdly, `tox -edocs` errors `AttributeError: 'NoneType' object has no attribute 'duration'` when I try to build them locally :(
