### ISSUE TITLE
QASM conversion fails when a gate is conditioned on a individual bit of a classical register

### ISSUE THREAD

**Issue by HwajungKang** [Qiskit/qiskit-terra#8700]
### Environment

- **Qiskit Terra version**: 0.21.2
- **Python version**: 3.7.7
- **Operating system**: Mac

### What is happening?

A quantum circuit with a gate conditioned on a single bit value of a classical register cannot be converted to a QASM string.

### How can we reproduce the issue?

```python
q = QuantumRegister(2, 'q')
c = ClassicalRegister(2, 'c')
qc = QuantumCircuit(q, c)
qc.h(0)
qc.cx(0, 1)
qc.measure(0, 0)
qc.x(1).c_if(c[0], 1)
print(qc)
qc.qasm()
```

/opt/miniconda3/lib/python3.7/site-packages/qiskit/circuit/instruction.py in _qasmif(self, string)
    438         if self.condition is None:
    439             return string
--> 440         return "if(%s==%d) " % (self.condition[0].name, self.condition[1]) + string
    441 
    442     def qasm(self):

AttributeError: 'Clbit' object has no attribute 'name'

### What should happen?

Expect to get a QASM string

**Comment by jakelishman** [comment]
The error message could be better here, but `QuantumCircuit.qasm` produces OpenQASM 2, and there's no way to represent single-bit conditions in OpenQASM 2.  This should work with the OpenQASM 3.0 exporter (in `qiskit.qasm3`), though OQ 3 support is still under active development, and isn't fully complete yet.

**Comment by HwajungKang** [comment]
I see. Thanks! @jakelishman

**Comment by jakelishman** [comment]
No worries!  I've just pushed #8701 that should improve the error message to better explain what's going on in this case.
