### ISSUE TITLE
Old classes are not accessible via qiskit.extensions

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#4365]
### Information

- **Qiskit Terra version**: 0.14.0
- **Python version**: All
- **Operating system**: Any

### What is the current behavior?

Running 
```
from qiskit.extensions import Cu3Gate
```
Raises an `ImportError`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Cu3Gate' from 'qiskit.extensions' (/home/mtreinish/git/qiskit/qiskit/.tox/lint/lib/python3.8/site-packages/qiskit/extensions/__init__.py)
```

as do other classes which were deprecated as part of the 0.13.0 release cleanup. It worked fine on qiskit-terra 0.13.0 (also without a deprecation warning, which I thought it would raise). This is a big breakage and needs to be fixed in a quick 0.14.1 release.

### Steps to reproduce the problem

```
from qiskit.extensions import Cu3Gate
```

### What is the expected behavior?

This works, this is likely fallout from rushing through #4035 

### Suggested solutions

Fix this
