### ISSUE TITLE
Cannot transpile multiple circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4707]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

backend = provider.backends.ibmq_vigo
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

job = transpile([qc, qc], backend)
```

gives:

/opt/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.15.0-py3.7-macosx-10.9-x86_64.egg/qiskit/compiler/transpile.py:445: UserWarning: All timestamps in backend properties are now in local time instead of UTC.
  if backend.properties():
Process ForkProcess-1:
Process ForkProcess-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/miniconda3/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'
TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'

**Comment by mtreinish** [comment]
I think this is caused by #4550 the multirprocessing stuff will need to pickle the arguments for each worker process and because of #4550 pickle doesn't know how to handle `PulseBackendConfiguration`. What I don't understand is why the ibmq provider is using the pulse backend configuration, I didn't think vigo was a pulse backend unless something changed with it since the last time I used it.

**Comment by nonhermitian** [comment]
I do not think Vigo is pulse enabled. However the notion of pulse or qasm backend is antiquated. The devices can be configured per provider. However, if pulse is one for one provider then the pulse params are pushed up for all.

**Comment by nonhermitian** [comment]
Note that this works just fine in previous versions, eg 0.19.6

**Comment by nonhermitian** [comment]
Also Vigo gives me :`QasmBackendConfiguration`

**Comment by mtreinish** [comment]
I don't know what would have changed in terra related to the backend configuration since 0.14.2 to cause this. Are you using the same version of the ibmq provider in the failure case? The only changes to backend configuration since the 0.14.x release are #4539 and #4652 which shouldn't change anything around this.

**Comment by nonhermitian** [comment]
I am using provider master...

**Comment by nonhermitian** [comment]
This still fails with the current provider `0.7.2` so seems to be a Terra issue.

**Comment by mtreinish** [comment]
> Also Vigo gives me :`QasmBackendConfiguration`

Well something is trying to pickle a `PulseBackendConfiguration` object in the script because:
```
TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'
```
will only come from a `PulseBackendConfiguration` object. That's the signature for that class, nothing else has those positional args.

Anyway I just pushed a fix for #4550 as #4711 and it fixes the error here, but the example script gets stuck on a different pickling error for me locally now:
```
TypeError: __init__() missing 1 required positional argument: 'provider'
```

My only guess is pickling a `IBMQBackend` object is failing now, because nothing in terra has `provider` as a positional argument. Looking at the ibmq provider code: https://github.com/Qiskit/qiskit-ibmq-provider/blob/0.7.2/qiskit/providers/ibmq/ibmqbackend.py#L93 it is using `provider` as a positional argument there. I'm thinking that pickle is getting confused because BaseBackend has a kwarg for provider not a positional arg: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/basebackend.py#L31

**Comment by jyu00** [comment]
`IBMQBackend` contains `AccountProvider`, which contains a list of all backends the provider has, including some that support pulse. This was the reason it tripped on `PulseBackendConfiguration` pickling.

Similarly, `AccountProvider` has `IBMQBackendService`, which is a child of `SimpleNamespace`. I'll fix this in provider.
