### ISSUE TITLE
`'NoneType' object has no attribute 'metadata'` when trying to serialize an openly controlled custom gate on `qiskit-terra==0.22.2` when it used to work on `qiskit-terra==0.21.1`

### ISSUE THREAD

**Issue by vtomole** [Qiskit/qiskit-terra#9107]
### Environment

- **Qiskit Terra version**: 0.21.2
- **Python version**: 3.8.13
- **Operating system**: Ubuntu

### What is happening?

I can't re-open https://github.com/Qiskit/qiskit-terra/issues/8794 and i don't know if the procedure is to create an new issue. If it's not, please close this and re-open https://github.com/Qiskit/qiskit-terra/issues/8794.

The reason I'm opening this is because the fix for the other issue didn't cover all the cases.

### How can we reproduce the issue?
```python
circuit = qiskit.QuantumCircuit(2)
circuit.append(CustomCXGate(ctrl_state="0"),[0, 1])
buf = io.BytesIO()
dump(circuit, buf)
```

This will throw an error

```
circuit.metadata, separators=(",", ":"), cls=metadata_serializer
AttributeError: 'NoneType' object has no attribute 'metadata'

```

### What should happen?

Should run with no errors.

**Comment by 1ucian0** [comment]
Reopening #8794 and closing this one.
