### ISSUE TITLE
Matplotlib drawer fails with style dict

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-terra#2422]
### Information

- **Qiskit Terra version**: master

### What is the current behavior?
If you don't provide a config to the matplotlib drawer, but you provide a style dict an error is raised `AttributeError: 'MatplotlibDrawer' object has no attribute '_style'` . I think this is because of the logic introduced in #2344, which results in the `self._style` variable never being initialised.

### Steps to reproduce the problem
Provide a style dict but no config

### Suggested solutions
Set the style to be the one provided by the user.

**Comment by nonhermitian** [comment]
yes, this is my fault as I did not even know that was an option at the time. The use of a dict here also does not match the other plotting routines like text where things like line_length are kwargs not a single dict
