### ISSUE TITLE
pulse delay instruction cause error when np.int is given

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#4078]
### What is the expected enhancement?

T1 experiment for example:
```python
delay_times = np.linspace(0, 200, 21, dtype=int)

for delay_time in delay_times:
    ...
    sched += Delay(delay_time, d0)
```

This program will cause an error:
```
AttributeError: 'numpy.int64' object has no attribute 'name'
```

np.int should be allowed for the `duration` of Delay instruction.

**Comment by taalexander** [comment]
This is a bug introduced by #3750 and the accompanying support for backward compatibility.

**Comment by enavarro51** [comment]
@taalexander Is this as simple as casting `duration` in `class Delay` to an int, or are there deeper ramifications? If it's not too deep, I can take this on.

**Comment by taalexander** [comment]
Other than adding a test to go along with your fix, I think its that simple 😄 .

**Comment by enavarro51** [comment]
One thing is that this would convert 3.5 to 3. Don't know if that's acceptable or not. The test for isinstance takes place in Instruction. I noticed that in the module Command that it imports numpy and uses isinstance(duration, (int, np.integer)). Is it acceptable to import numpy into Instruction and use this form of isinstance? Seems cleaner and more consistent to me.

**Comment by taalexander** [comment]
This seems fine to me.

**Comment by enavarro51** [comment]
Thanks. Then I'm on it.
